### ISSUE TITLE
v1 checklist

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1011]
* [ ] make sure expectations are set in readme and clustering docs re MT by itself not having cluster management built-in
* [ ] go over all docs and update as needed
* [ ] make sure we have a good guide to setup a cluster
* [ ] try out installation guides again and assure proper functioning
* [ ] version internal cluster communication api
* [ ] version admin api (?). 
* [ ] declare what our api is for semver (probably don't include metric names)
* [ ] think ahead of manual intervention scenarios that might happen in the future and how we can avoid them
* [ ] address all tickets with label `breaking-xxx`

**Comment by Dieterbe** [comment]
+ I think we should review the supported versions of runtime dependencies and included versions of libraries, and make sure stuff is up to date

**Comment by Dieterbe** [comment]
https://github.com/grafana/metrictank/labels/breaks-api
https://github.com/grafana/metrictank/labels/breaks-config
https://github.com/grafana/metrictank/labels/breaks-monitoring
