### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1319]
# Roadmap
Note: this is the roadmap covering the entire "Graphite Platform" at Grafana Labs. It includes metrictank, graphite, tsdb-gw, carbon-relay-ng and hosted-metrics-api.

It is indicative, incomplete and subject to change.

## General
- [ ] Sharding by tags - #1123 
- [ ] Meta tags - #660 
- [ ] Formalize tag format. Shared validation library - #1216 
- [ ] Rollup indicator in Grafana -> return metadata with render responses - https://github.com/grafana/grafana/issues/11700
- [ ] Index RAM optimizations v1: string interning - #1261 
- [ ] Dot munging overhaul - needed tech debt fixing for string interning - #1008 
- [ ] Kafka TLS and Auth support - #1277 
- [ ] Refactor cluster migration
- [ ] Stats alongside query responses - #1130 
- [ ] Index reporting (break down of series counts by subpath)
- [ ] Opentracing sampling, on-demand tracing of requests
- [ ] Slow query log
- [ ] RAM reductions (stream chunks instead of point slices, jit decoding, etc)
- [ ] Graphite render api 100% native - #1227 

## Carbon-relay-ng
- [ ] Agent v2 (with insights into config, support to push config updates, feedback to customers about perf issues, HA without out-of-order issues) - https://github.com/graphite-ng/carbon-relay-ng/issues/347
- [ ] Carbon-relay-ng counter aggregator - https://github.com/graphite-ng/carbon-relay-ng/issues/344
- [ ] Carbon-relay-ng fix aggregator unreliable under cpu load - https://github.com/graphite-ng/carbon-relay-ng/issues/241
- [ ] Carbon-relay-ng test all packages / packaging bugs - https://github.com/graphite-ng/carbon-relay-ng/issues/348

## tsdb-gw
- [ ] Rate limits on inbound rate + active series and queries - https://github.com/raintank/tsdb-gw/issues/134

## Operations
- [ ] Management UI for private cloud / enterprise customers to administer their cluster
- [ ] Non-k8s installation
- [ ] Continuous deployment to GrafanaCloud
- [ ] Clustering/scalability refactor
- [ ] Tooling for bigtable on par with cassandra
- [ ] Whisper importer for bigtable - #1162 

## Documentation
- [ ] Platform functionality, api's (ingestion, querying, metrics management) (cloud)
- [ ] Administrator Guide (on-prem)

**Comment by wlargou** [comment]
For new deployment, do you recommend to go with MetricTank as backend of Graphite ? And what's the roadmap for the two platforms, is there plans for merging them sometime in the near future ?

**Comment by Dieterbe** [comment]
There are no plans to merge graphite and metrictank. they are separate projects. if you want run a large graphite installation, then metrictank is a good/scaleable way to do so. but for small installations it's overkill. you can also look at Grafana Cloud and then you don't need to run anything yourself (and there's a free tier)

**Comment by wlargou** [comment]
Thanks for your feedback, the customer opted for Prometheus/Grafana, I guess that will be enough for his mid-sized environment.
